{
 "title": "Lean Ethereum Client Interop Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latest finalized slot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(lean_latest_finalized_slot{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest justified slot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "max(lean_latest_justified_slot{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Head slot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "max(lean_head_slot{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum(lean_validators_count{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Latest finalized slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "lean_latest_finalized_slot{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Latest justified slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "expr": "lean_latest_justified_slot{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Head slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "lean_head_slot{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Head - Finalized  delay (slots)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "lean_head_slot{job=~\"$job\"} - lean_latest_finalized_slot{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Head - Justified delay (slots)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "lean_head_slot{job=~\"$job\"} - lean_latest_justified_slot{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Justified - Finalized  delay (slots)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "lean_latest_justified_slot{job=~\"$job\"} - lean_latest_finalized_slot{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Validators Per Node",
   "type": "piechart",
   "description": "Number of validators attached to each node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(lean_validators_count{job=~\"$job\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "lean_validators_count{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Validators Per Node",
   "type": "timeseries",
   "description": "Number of validators attached to each node",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum(lean_validators_count{job=~\"$job\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "lean_validators_count{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "PQ Signature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Time taken to sign a PQ signature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, (rate(lean_pq_signature_attestation_signing_time_seconds_bucket{job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Time taken to verify a PQ signature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, (rate(lean_pq_signature_attestation_verification_time_seconds_bucket{job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Fork-Choice", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Block processing time",
   "type": "timeseries",
   "description": "Time taken to process block in fork-choice",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  rate(lean_fork_choice_block_processing_time_seconds_bucket{job=~\"$job\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 } },
  { "title": "Attestations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "FC Valid attestations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job) (increase(lean_attestations_valid_total{job=~\"$job\"}[$__rate_interval]))[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "FC Invalid attestations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 47 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job) (increase(lean_attestations_invalid_total{job=~\"$job\"}[$__rate_interval]))[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "FC Attestations validation time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(lean_attestation_validation_time_seconds_bucket{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "STF Processed attestations",
   "type": "timeseries",
   "description": "Total number of attestations processed in state transition function",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job) (increase(lean_state_transition_attestations_processed_total{job=~\"$job\"}[$__rate_interval]))[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "STF Attestations processing time",
   "type": "timeseries",
   "description": "Time taken to process attestations in state transition function",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n rate(lean_state_transition_attestations_processing_time_seconds_bucket{job=~\"$job\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "State Transition", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "State transition time",
   "type": "timeseries",
   "description": "Time taken to process state transition function",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  rate(lean_state_transition_time_seconds_bucket{job=~\"$job\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Block processing time",
   "type": "timeseries",
   "description": "Time taken to process block in state transition function",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  rate(lean_state_transition_block_processing_time_seconds_bucket{job=~\"$job\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Processed slots",
   "type": "timeseries",
   "description": "Total number of processed slots in state transition function",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job) (increase(lean_state_transition_slots_processed_total{job=~\"$job\"}[$__rate_interval]))[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Slots processing time",
   "type": "timeseries",
   "description": "Time taken to process slots in state transition function",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n rate(lean_state_transition_slots_processing_time_seconds_bucket{job=~\"$job\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}