{
 "title": "PQ Devnet 0 Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latest finalized slot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lean_latest_finalized_slot{job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest justified slot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lean_latest_justified_slot{job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Head slot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lean_head_slot{job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 } },
  {
   "title": "Head - Finalized",
   "type": "stat",
   "description": "Head to finalized distance (slots)",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lean_head_slot{job=~\"$job\"} - lean_latest_finalized_slot{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Head - Justified",
   "type": "stat",
   "description": "Head to justified distance (slots)",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lean_head_slot{job=~\"$job\"} - lean_latest_justified_slot{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Justified - Finalized",
   "type": "stat",
   "description": "Justified but unfinalized (slots)",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lean_latest_justified_slot{job=~\"$job\"} - lean_latest_finalized_slot{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lean_validators_count{job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "PQ Signature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "PQ signing time",
   "type": "timeseries",
   "description": "Time taken to sign a PQ signature",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, (rate(lean_pq_signature_attestation_signing_time_seconds{job=~\"$job\"}[$__rate_interval])))\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "PQ verification time",
   "type": "timeseries",
   "description": "Time taken to verify a PQ signature",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, (rate(lean_pq_signature_attestation_verifying_time_seconds_bucket{job=~\"$job\"}[$__rate_interval])))\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Fork-Choice", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Block processing time",
   "type": "timeseries",
   "description": "Time taken to process block in fork-choice",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, (rate(lean_fork_choice_block_processing_time_seconds_bucket{job=~\"$job\"}[$__rate_interval])))\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 } },
  { "title": "Attestations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "FC Valid attestations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job) (increase(lean_attestations_valid_total{job=~\"$job\"}[$__rate_interval]))[5m:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FC Invalid attestations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "avg_over_time(\n  sum by (job) (increase(lean_attestations_invalid_total{job=~\"$job\"}[$__rate_interval]))[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "FC Attestations validation time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(lean_attestation_validation_time_seconds_bucket{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "STF Processed attestations",
   "type": "timeseries",
   "description": "Total number of attestations processed in state transition function",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(\n  (rate(lean_state_transition_attestations_processed_total{job=~\"$job\"}[$__rate_interval])* 4)[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "STF Attestations processing time",
   "type": "timeseries",
   "description": "Time taken to process attestations in state transition function",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n rate(lean_state_transition_attestations_processing_time_seconds_bucket{job=~\"$job\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "State Transition", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "State transition time",
   "type": "timeseries",
   "description": "Time taken to process state transition function",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  rate(lean_state_transition_time_seconds_bucket{job=~\"$job\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Block processing time",
   "type": "timeseries",
   "description": "Time taken to process block in state transition function",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  rate(lean_state_transition_block_processing_time_seconds_bucket{job=~\"$job\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Processed slots",
   "type": "timeseries",
   "description": "Total number of processed slots in state transition function",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "avg_over_time(\n  (rate(lean_state_transition_slots_processed_total{job=~\"$job\"}[$__rate_interval]) * 4)[5m:]\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Slots processing time",
   "type": "timeseries",
   "description": "Time taken to process slots in state transition function",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n rate(lean_state_transition_slots_processing_time_seconds_bucket{job=~\"$job\"}[$__rate_interval])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}